name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POETRY_HOME: "/opt/poetry"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12
      - name: install poetry
        run: |
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.7.1
          $POETRY_HOME/bin/poetry --version
      - name: add poetry to path
        run: echo "${POETRY_HOME}/bin" >> $GITHUB_PATH
      - name: install dependencies and build
        run: poetry install
      - name: run tests
        run: poetry run tox -m unit
      - name: run integration tests
        env:
          gds_license: ${{ secrets.GDS_LICENSE }}
        run: |
          LICENSE_FILE=${{ runner.temp }}/license.tmp
          echo "${gds_license}" > $LICENSE_FILE
          GDS_LICENSE_FILE=$LICENSE_FILE poetry run tox -m integration
